### PR TITLE
RSL hash substitution

### PR DESCRIPTION
**Pull request by bsideup**
Hi!

I would like to share with you my improvement to rslUrls. With this code you will be allowed to use:

``` xml
<rslUrls>
    <url>{contextRoot}/rsls/{artifactId}-{hash}.{extension}</url>
</rslUrls>
```

where hash is a md5 hash of library SWC file. It's very useful for caching RSLs, no need to worry about versions and other things - if RSL is changed, it will have different name ( for example: advancedgrids-329f05f6505656a1e8a281c838e97564.swz ).

Tested in 5.X branch (unfortunately our projects are still on 5.0-beta and 4.6.b.23130), but should works fine in 7.X because changes are backward compatible. 

Thanks!

### CODE REVIEW

**Comment by chrisdutz** [comment]
Hi Sergey,

Thanks for that Submission ... wonder why I didn't get the pull request notification for that ... hmmm ... strange.

I'll have a look at this ... would be really cool, if you could add a testcase for the testsuite for this ... don't want to add Features which don't have test-cases.

Chris

---

Von: Sergey Egorov notifications@github.com
Gesendet: Mittwoch, 29. Januar 2014 21:54
An: chrisdutz/flexmojos
Betreff: [flexmojos] RSL hash substitution (#7)

Hi!

I would like to share with you my improvement to rslUrls. With this code you will be allowed to use:

<rslUrls>
    <url>{contextRoot}/rsls/{artifactId}-{hash}.{extension}</url>
</rslUrls>

where hash is a md5 hash of library SWC file. It's very useful for caching RSLs, no need to worry about versions and other things - if RSL is changed, it will have different name ( for example: advancedgrids-329f05f6505656a1e8a281c838e97564.swz ).

Tested in 5.X branch (unfortunately our projects are still on 5.0-beta and 4.6.b.23130), but should works fine in 7.X because changes are backward compatible.

Thanks!

---

You can merge this Pull Request by running

  git pull https://github.com/bsideup/flexmojos feature/rsl-hash-substitution

Or view, comment on, or merge it at:

  https://github.com/chrisdutz/flexmojos/pull/7

Commit Summary
-   rsl hash substitution

File Changes
-   M flexmojos-maven-plugin/src/main/java/net/flexmojos/oss/plugin/utilities/MavenUtils.javahttps://github.com/chrisdutz/flexmojos/pull/7/files#diff-0 (16)
-   M flexmojos-maven-plugin/src/main/java/net/flexmojos/oss/plugin/war/CopyMojo.javahttps://github.com/chrisdutz/flexmojos/pull/7/files#diff-1 (12)

Patch Links:
-   https://github.com/chrisdutz/flexmojos/pull/7.patch
-   https://github.com/chrisdutz/flexmojos/pull/7.diff

##

**Comment by bsideup** [comment]
Ok, agree with you:) I will add test case little bit later today.

**Comment by bsideup** [comment]
Done.

Do you have any CI server that show status for pull requests? I would like to test my changes because i'm unable to setup all deps locally (especially Flex SDK:))

**Comment by chrisdutz** [comment]
I usually apply them locally and let it build on one of my PCs which is Idling around :-)

So I would update my local copy, apply the changes in the pull-request and as soon as it's green, commit it.

Chris

---

Von: Sergey Egorov notifications@github.com
Gesendet: Donnerstag, 30. Januar 2014 12:39
An: chrisdutz/flexmojos
Cc: Christofer Dutz
Betreff: Re: [flexmojos] RSL hash substitution (#7)

Do you have any CI server that show status for pull requests? I would like to test my changes because i'm unable to setup all deps locally (especially Flex SDK:))

##

**Comment by bsideup** [comment]
Ok, cool:)

Keep me in touch!

**Comment by bsideup** [comment]
Hi, Chris!

How it's going?

**Comment by chrisdutz** [comment]
Hi Sergey,

unfortunately I didn't have the time yet to check your stuff, as I'm currently sort of drowning in work on my day-job :-(

Chris

---

Von: Sergey Egorov notifications@github.com
Gesendet: Donnerstag, 6. Februar 2014 13:27
An: chrisdutz/flexmojos
Cc: Christofer Dutz
Betreff: Re: [flexmojos] RSL hash substitution (#7)

Hi, Chris!

How it's going?

##

**Comment by bsideup** [comment]
Too sad :(

**Comment by fljot** [comment]
// Just to bring up some attention.
Awesome feature indeed.
Situation: our project has several modules, which are used as RSLs. Once I update, let's say, one of the SWC in graphics module and mvn install that thing locally (to get confirmation first that it's all okay and I can push it to git and build server) — I can build the whole project and be sure, that RSL names are updated, and even server (Cloudfront) won't cache it, and, therefore, tester will actually get the proper RSL loaded.

**Comment by chrisdutz** [comment]
Hi,

I haven't forgotten you. Unfortunately I am plaqued by a customer that keeps on bringing in one Change after the other. I promise this will be the first Thing I'll add. But I just had a look at github a while ago and coudln't find a pull request with the patch or a testcase ... did you prepare a testcase for the testsuite that tests your Feature? As I said, I don't want to add new Features without having testcases for them.

Chris

---

Von: Pavel Pevnitskiy notifications@github.com
Gesendet: Freitag, 28. Februar 2014 11:40
An: chrisdutz/flexmojos
Cc: Christofer Dutz
Betreff: Re: [flexmojos] RSL hash substitution (#7)

// Just to bring up some attention.
Awesome feature indeed.
Situation: our project has several modules, which are used as RSLs. Once I update, let's say, one of the SWC in graphics module and mvn install that thing locally (to get confirmation first that it's all okay and I can push it to git and build server) - I can build the whole project and be sure, that RSL names are updated, and even server (Cloudfront) won't cache it, and, therefore, tester will actually get the proper RSL loaded.

##

**Comment by bsideup** [comment]
See https://github.com/bsideup/flexmojos/commit/c4cebd2646db2f2b67c1206879b5d671d71abea4

**Comment by chrisdutz** [comment]
Ahh ... ok ... now it's there :-) I'll check it out as soon as possible.

Chris

---

Von: Sergey Egorov notifications@github.com
Gesendet: Freitag, 28. Februar 2014 13:36
An: chrisdutz/flexmojos
Cc: Christofer Dutz
Betreff: Re: [flexmojos] RSL hash substitution (#7)

See bsideup@c4cebd2https://github.com/bsideup/flexmojos/commit/c4cebd2646db2f2b67c1206879b5d671d71abea4

##

**Comment by bsideup** [comment]
Ok. Thanks!

**Comment by chrisdutz** [comment]
Ok ... so I had a look at your changes and they seem to be valid. I will however drop this pull request, as you tweaked the original copy-mojo test. I rather prefer to have individual tests for individual features. Velo tweaked a lot of test over time so he could use them for all different aspects of Flexmojos. Unfortunately you never know in a few years why something was done that way. Therefore I have started to change the testsuite to test one feature with one individual test. This way someone trying to understand a feature can actually learn something from the testsuite instead of get irritated. Hope that's ok with you ... at least the testsuite is currently running on my backup build slave.

**Comment by bsideup** [comment]
I can extract test in current pull request, it's not necessary to drop it:)

**Comment by chrisdutz** [comment]
Well the testsuite execution just finished, but it failled. The test seems to have someproblems:

Tests run: 123, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2,947.067 sec <<< FAILURE!
copyFlexResoucesWithHashRsls(net.flexmojos.oss.tests.concept.CopyMojoTest)  Time elapsed: 18.932 sec  <<< FAILURE!
java.lang.AssertionError: Unable to parse 
D:\Projects\flexmojos\trunk\flexmojos-testing\flexmojos-test-harness\target\projects\concept\copy-flex-resources-with-hash_copyFlexResoucesWithHashRsls\target\copy-swf-1.0-SNAPSHOT-configs.xml
    at org.testng.Assert.fail(Assert.java:73)
    at net.flexmojos.oss.tests.AbstractFlexMojosTests.getFlexConfigReport(AbstractFlexMojosTests.java:473)
    at net.flexmojos.oss.tests.concept.CopyMojoTest.copyFlexResoucesWithHashRsls(CopyMojoTest.java:68)
Caused by: java.io.FileNotFoundException: D:\Projects\flexmojos\trunk\flexmojos-testing\flexmojos-test-harness\target\projects\concept\copy-flex-resources-with-hash_copyFlexResoucesWithHashRsls\target\copy-swf-1.0-SNAPSHOT-configs.xml (Das System kann den angegebenen Pfad nicht finden)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
    at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
    at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
    at net.flexmojos.oss.tests.AbstractFlexMojosTests.getFlexConfigReport(AbstractFlexMojosTests.java:469)
    ... 34 more
testLocalizationChain(net.flexmojos.oss.tests.concept.L10NTest)  Time elapsed: 57.503 sec  <<< FAILURE!
org.apache.maven.it.VerificationException: Exit code was non-zero: 1; command line and log = 

Having a look it seems not to be related to me splitting this up into two tests. I'll check the details tomorrow.

Chris

**Comment by bsideup** [comment]
ok, i will review test tomorrow and find what's wrong, i didn't test it by myself because it's hard to setup environment for it. But i will try

**Comment by chrisdutz** [comment]
Ok .. so I updated the test to correctly get the right configuration-report, but the test still fails, because the content of that file doesn't seem quite right:

```
    @Test
    public void copyFlexResoucesWithHashRsls()
            throws Exception
    {
        final File testDir = getProject( "/concept/copy-flex-resources-with-hash" );
        test( testDir, "install", "-DconfigurationReport" );

        final File warFile = new File( testDir, "war/target/copy-war-1.0-SNAPSHOT.war" );
        Assert.assertTrue( warFile.exists(), "War file not found!" );

        final ZipFile war = new ZipFile( warFile );
        Assert.assertNotNull( war.getEntry( "copy-swf-1.0-SNAPSHOT.swf" ), "Swf entry not present at war!" );
        Assert.assertNotNull( war.getEntry( "copy-swf-1.0-SNAPSHOT-module1.swf" ), "Swf entry not present at war!" );
        Assert.assertNotNull( war.getEntry( "copy-swf-1.0-SNAPSHOT-module2.swf" ), "Swf entry not present at war!" );

        final FMVerifier swfVerifier = getVerifier(new File(testDir, "swf"));
        final Xpp3Dom appConfigReportDOM = getFlexConfigReport(swfVerifier, "copy-swf", "1.0-SNAPSHOT");
        final Xpp3Dom rslPath = appConfigReportDOM.getChild("runtime-shared-library-path");

        final File librarySwcFile = new File(rslPath.getChild("path-element").getValue());
        final byte[] artifactBytes = FileUtils.readFileToByteArray(librarySwcFile);
        final String hash = DigestUtils.md5Hex(artifactBytes);

        Assert.assertNotNull( war.getEntry( "rsls/framework-" +
                        getArtifactVersion(getFlexFrameworkGroupId(), "framework") + "-" + hash + ".swf" ),
                "Rsl entry not present at war!" );
    }
```

because this is what I can see in the copy-swf-1.0-SNAPSHOT-configs.xml

```
   <runtime-shared-library-path>
      <path-element>E:\Projects\Flexmojos\flexmojos-6.x\trunk\flexmojos-testing\flexmojos-test-harness\target\local-repository\org\apache\flex\framework\framework\4.11.0.20131017\framework-4.11.0.20131017.swc</path-element>
      <rsl-url>rsls/framework-4.11.0.20131017-{hash}.swf</rsl-url>
   </runtime-shared-library-path>
```

So to me it looks as if the "{hash}" is not correctly replaced.

**Comment by bsideup** [comment]
Weird because it works in several our projects (patched 5.x flexmojos version). 

Maybe i will create test in 5.x version (which is easy to test for me) and you will test it in 6.x?

**Comment by chrisdutz** [comment]
Ok .. the reason was for me testing my patched test on a machine without the updated FM installed. With the updated plugin in my local maven repo the test actually passed. I am currently applying this to the FM7 branch. If this works, I'll simply merge this to FM6

**Comment by bsideup** [comment]
Awesome! Thanks!

**Comment by chrisdutz** [comment]
Ok ... so I fixed the test and validated all ... the build ran smooth and comitted the changes as well as added an updated 7.0.0-SNAPSHOT which is currently being deployed.

**Comment by bsideup** [comment]
Ok, good. Hope next time my pull request will suit you to accept "as is" :)

Btw, no plans for public CI server for FM? Will be awesome

**Comment by chrisdutz** [comment]
I had setup a CI Server for FM, but in order to be able to run the testsuite it needed to be a Windows machine. I Had an Amazon EC2 node for about a year and also tried with an Microsoft Azure, but the costs were too high. I therefore settled to doing local CI builds on my own machines as I was the only one actually doing commits.

Chris

Von: Sergey Egorov [mailto:notifications@github.com]
Gesendet: Samstag, 1. März 2014 17:29
An: chrisdutz/flexmojos
Cc: Christofer Dutz
Betreff: Re: [flexmojos] RSL hash substitution (#7)

Ok, good. Hope next time my pull request will suit you to accept "as is" :)

Btw, no plans for public CI server for FM? Will be awesome

**Comment by bsideup** [comment]
I can help you:) that's what i'm doing on my regular job ;) I will need a little bit help from you to setup, and also provide servers, so it will not cost you a lot of time, but should be very helpful for future project development.

**Pull request closed without merging**
