### PR TITLE
Add arbitrary props to air descriptor template

### PR DESCRIPTION
**Pull request by SamBarker**
This patch allows the people to configure a map of properties to be substituted into the air descriptor template.

We use it to set the version number to the final build number at all times and to inject a separate versionLabel.

### CODE REVIEW

**Comment by chrisdutz** [comment]
Could you whip up a small sample project that I could add to the testsuite? Have you run the complete testsuite with your changes? Was it successfull?

**Comment by SamBarker** [comment]
I haven't got the tesetsuite to run full stop (haven't tried in ages). But will give it a go and add a sample project

**Comment by chrisdutz** [comment]
If you use an Adobe Flex FDK the testsuite should pass. This was one of the things that took me ages to get running again and this is also the reason why I won't apply stuff that breaks the testsuite.

**Comment by chrisdutz** [comment]
If however you use an Adobe FDK, all tests regarding the "caching" will definitely fail as the Adobe FDKs don't come with signed framework RSLs.

**Comment by chrisdutz** [comment]
Just merged your stuff ... ran the complete testsuite about 5 times now (release sort of doesn't go through :-(). So your changes will be in the official FM 6.0.0 release that I'll have out of the door some time the release:prepare allows me to push my changes back to github.

**Comment by SamBarker** [comment]
Thanks very much. I'll try and get the test suite going locally and add tge
samples.
On 23 Feb 2013 16:47, "Christofer Dutz" notifications@github.com wrote:

> Just merged your stuff ... ran the complete testsuite about 5 times now
> (release sort of doesn't go through :-(). So your changes will be in the
> official FM 6.0.0 release that I'll have out of the door some time the
> release:prepare allows me to push my changes back to github.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chrisdutz/flexmojos/pull/5#issuecomment-13993044.

## 

---

_IMPORTANT NOTICE_: MahiFX Limited (_MahiFX_), (company no. 2446590) is 
registered in New Zealand. MahiFX is authorised and regulated by the 
Australian Securities and Investment Commission ARBN 152 535 085, AFSL 
414198. This email, its attachments and any rights attaching hereto are 
confidential and intended exclusively for the person to whom the email is 
addressed. If you are not the intended recipient, do not read, copy, 
disclose or use the contents in any way. Please notify the sender by return 
email and destroy the email and attachments immediately. MahiFX does not 
accept any liability for any changes made to this email or attachments 
after sending by MahiFX. You must scan this email and attachments for 
viruses. The opinions expressed are not necessarily those of MahiFX. MahiFX 
accepts no liability for any loss, damage or consequence, whether caused by 
our own negligence or not, resulting directly or indirectly from the use of 
this email and attachments.

For more information about MahiFX Limited see mahifx.com.

**Pull request merged**
